name: Countdown

args:

  path: TheBlackCat22/countdown
  train_size: 327680
  test_size: 1024
  train_levels: 
    - 0
    - 1
    - 2
    - 3
  test_levels:
    - 0
    - 1
    - 2
    - 3
    - 4

  system_content: "You are a helpful assistant. You first thinks about the reasoning process in the mind and then provides the user with the answer.\n"
  user_content: "Using the numbers {question}, create an equation that equals {answer}. You can use basic arithmetic operations (+, -, *, /) and each number can only be used once. Show your work in <think> </think> tags. And return the final answer in <answer> </answer> tags, for example <answer> (1 + 2) / 3 </answer>."
  assistant_content: "Let me solve this step by step.\n<think>"

  format_reward: 0.1
  format_reward_fn: FormatReward
  correctness_reward: 0.9
  correctness_reward_fn: CountdownCorrectnessReward

  max_steps: 1600
  max_prompt_length: 1000
  max_completion_length: 512