WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=6,4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=train task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=balanced
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=6,4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=train task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=cosine
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=6,4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=train task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=6,4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=train task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian algorithm.training.scheduler_params.mu_exp=0.25 algorithm.training.scheduler_params.sigma=0.75
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=6,4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=train task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian algorithm.training.scheduler_params.mu_exp=0.75 algorithm.training.scheduler_params.sigma=0.25

WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=inference task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=balanced
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=inference task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=cosine
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=inference task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=inference task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian algorithm.training.scheduler_params.mu_exp=0.25 algorithm.training.scheduler_params.sigma=0.75
WANDB_PROJECT=Sys2Bench ROOT_PATH=/mnt/data/shared/blakeo/LM-Reasoning/Reasoning CUDA_VISIBLE_DEVICES=4 accelerate launch --num_processes 1 --main_process_port=29001 --config_file methods/RL/deep_speed.yaml  methods/RL/main.py mode=inference task=gsm8k algorithm=grpo model=qwen15 algorithm.training.curriculum_schedule=gaussian algorithm.training.scheduler_params.mu_exp=0.75 algorithm.training.scheduler_params.sigma=0.25